Repository hmcts/tax-tribunals-datacapture, pull requests merged in 2024-11, with the labels that each got.

#348 RST-6999 and RST-6998 test fix
  .env.test
  features/step_definitions/cookie_steps.rb
  features/support/page_objects/base_page.rb
  features/support/page_objects/home_page.rb
  lib/tasks/test.rake
  spec/controllers/status_controller_spec.rb
  spec/services/glimr_direct_api_client/api_spec.rb
Labels: enable_keep_helm, ns:tax-tribunals, prd:tax-tribunals, rel:tax-tribunals-application-pr-348

#349 RST-6930 - Updated GovUk-Frontend to 5.7.1 and removed Puppeteer.
  Jenkinsfile_CNP
  package.json
  yarn.lock
Labels: enable_keep_helm, ns:tax-tribunals, prd:tax-tribunals, rel:tax-tribunals-application-pr-349

#347 RST-6968 - Move initial form saves to after language selection step
  README.md
  app/controllers/steps/appeal/case_type_controller.rb
  app/controllers/steps/challenge/decision_controller.rb
  app/controllers/steps/closure/case_type_controller.rb
  app/controllers/steps/details/user_type_controller.rb
  app/forms/steps/challenge/decision_form.rb
  features/appeal_case_type.feature
  features/challenge_decision.feature
  features/closure_case_type.feature
  features/user_type.feature
  spec/controllers/steps/challenge/decision_controller_spec.rb
  spec/controllers/steps/details/user_type_controller_spec.rb
Labels: enable_keep_helm, ns:tax-tribunals, prd:tax-tribunals, rel:tax-tribunals-application-pr-347
