Repository hmcts/tax-tribunals-datacapture, pull requests merged in 2025-02, with the labels that each got.

#365 RST-6980 reminder emails not sent and incorrect send times
  app/mailers/notify_mailer.rb
  app/services/tax_tribs/reminder_rule_set.rb
  charts/tax-tribunals-application/Chart.yaml
  charts/tax-tribunals-application/values.yaml
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/sidekiq.rb
  config/sidekiq.yml
  sidekiq.sh
  spec/services/tax_tribs/reminder_rule_set_spec.rb
Labels: enable_keep_helm, ns:tax-tribunals, prd:tax-tribunals, rel:tax-tribunals-application-pr-365

#411 Minor gem updates
  Gemfile.lock
Labels: ns:tax-tribunals, prd:tax-tribunals, rel:tax-tribunals-application-pr-411

#414 Minor gem updates
  Gemfile.lock
Labels: ns:tax-tribunals, prd:tax-tribunals, rel:tax-tribunals-application-pr-414

#339 RST-6770 - update welsh and english govnotify templates
  charts/tax-tribunals-application/Chart.yaml
  charts/tax-tribunals-application/values.yaml
Labels: ns:tax-tribunals, prd:tax-tribunals, rel:tax-tribunals-application-pr-339

#421 Gem updates v9
  .rubocop.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  Jenkinsfile_CNP
  app/controllers/users/logins_controller.rb
  app/controllers/users/registrations_controller.rb
Labels: ns:tax-tribunals, prd:tax-tribunals, rel:tax-tribunals-application-pr-421
